Added parameters in Query Params and 403 response and your body results
stone-co/stone-api-docs pull request #196
Opened 2021-03-09 19:19 UTC by bmrbruno

2021-03-10 12:45 UTC, pedroyremolo approved these changes

2021-03-10 22:13 UTC, agabiandrade requested changes
Ei Bruno, alguns pontos:

1) O account_id é obrigatório, pode colocar mais um * ali.
2) Não entendi o JSON ali no meio. Não achei ele na doc interna nem na que a gente já tinha.

O restante tá ok! Consegue fazer essas alterações acima please? :)

2021-03-11 12:18 UTC, bmrbruno commented
Oi Gabi, na documentação interna existe um JSON "escondido", basta clicar no botão copy ao lado do "Query Params", achei que combinou bem o Json ali pois exemplificou todos os parâmetros! Quanto ao account_id, estarei colocando o * conforme solicitado!

2021-03-11 16:40 UTC, bmrbruno commented
Ei Bruno, alguns pontos:

O account_id é obrigatório, pode colocar mais um * ali.
Não entendi o JSON ali no meio. Não achei ele na doc interna nem na que a gente já tinha.
O restante tá ok! Consegue fazer essas alterações acima please? :)


** Alterações realizadas conforme solicitado!!!!!!

2021-03-17 18:41 UTC, agabiandrade approved these changes

2021-03-17 18:59 UTC, merged